on:
  push:
    branches:
      - master
name: Deploy master branch
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: npm install
      uses: actions/setup-node@v1
      with:
        node-version: '13'
    - name: Remove files that prevent successful deployment
      run: rm README.md && rm LICENSE.md && rm CONTRIBUTING.md && rm -rf docs/
    - run: npm install
    - name: serverless deploy
      uses: jackdcasey/github-action@python3.8-nodejs13
      with:
        args: deploy
      env:
        # SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
        # or if using AWS creds directly
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}